// Mirrored 1:1 from apps/api's domain/constant/secret-type.constant.ts.
// No shared package between the two apps, so this is kept in sync by hand
// (same approach datatector's own web app takes for its enums).
export enum ESecretType {
  AWS_ACCESS_KEY_ID = 'aws_access_key_id',
  GITHUB_PAT = 'github_pat',
  GITHUB_OAUTH_TOKEN = 'github_oauth_token',
  GITHUB_APP_TOKEN = 'github_app_token',
  GITHUB_REFRESH_TOKEN = 'github_refresh_token',
  GITLAB_PAT = 'gitlab_pat',
  SLACK_TOKEN = 'slack_token',
  SLACK_WEBHOOK_URL = 'slack_webhook_url',
  STRIPE_LIVE_SECRET_KEY = 'stripe_live_secret_key',
  STRIPE_TEST_SECRET_KEY = 'stripe_test_secret_key',
  STRIPE_LIVE_PUBLISHABLE_KEY = 'stripe_live_publishable_key',
  STRIPE_RESTRICTED_KEY = 'stripe_restricted_key',
  TWILIO_API_KEY = 'twilio_api_key',
  TWILIO_ACCOUNT_SID = 'twilio_account_sid',
  SENDGRID_API_KEY = 'sendgrid_api_key',
  MAILGUN_API_KEY = 'mailgun_api_key',
  MAILCHIMP_API_KEY = 'mailchimp_api_key',
  SQUARE_ACCESS_TOKEN = 'square_access_token',
  SQUARE_OAUTH_SECRET = 'square_oauth_secret',
  NPM_ACCESS_TOKEN = 'npm_access_token',
  PYPI_UPLOAD_TOKEN = 'pypi_upload_token',
  DOCKERHUB_PAT = 'dockerhub_pat',
  JWT_TOKEN = 'jwt_token',
  GOOGLE_API_KEY = 'google_api_key',
  GOOGLE_OAUTH_CLIENT_SECRET = 'google_oauth_client_secret',
  FIREBASE_CLOUD_MESSAGING_KEY = 'firebase_cloud_messaging_key',
  DISCORD_BOT_TOKEN = 'discord_bot_token',
  DISCORD_WEBHOOK_URL = 'discord_webhook_url',
  TELEGRAM_BOT_TOKEN = 'telegram_bot_token',
  SHOPIFY_ACCESS_TOKEN = 'shopify_access_token',
  SHOPIFY_SHARED_SECRET = 'shopify_shared_secret',
  SHOPIFY_PRIVATE_APP_TOKEN = 'shopify_private_app_token',
  FACEBOOK_ACCESS_TOKEN = 'facebook_access_token',
  TWITTER_BEARER_TOKEN = 'twitter_bearer_token',
  PRIVATE_KEY_PEM = 'private_key_pem',
  DIGITALOCEAN_PAT = 'digitalocean_pat',
  DIGITALOCEAN_OAUTH_TOKEN = 'digitalocean_oauth_token',
  PLANETSCALE_PASSWORD = 'planetscale_password',
  PLANETSCALE_API_TOKEN = 'planetscale_api_token',
  HASHICORP_VAULT_TOKEN = 'hashicorp_vault_token',
  AIRTABLE_API_KEY = 'airtable_api_key',
  OPENAI_API_KEY = 'openai_api_key',
  ANTHROPIC_API_KEY = 'anthropic_api_key',
  BRAINTREE_ACCESS_TOKEN = 'braintree_access_token',
  OPENSSH_PRIVATE_KEY = 'openssh_private_key',
  PGP_PRIVATE_KEY_BLOCK = 'pgp_private_key_block',
  GCP_SERVICE_ACCOUNT_KEY = 'gcp_service_account_key',
  AZURE_STORAGE_ACCOUNT_KEY = 'azure_storage_account_key',
  NEW_RELIC_API_KEY = 'new_relic_api_key',
  POSTMAN_API_KEY = 'postman_api_key',
  DATABRICKS_TOKEN = 'databricks_token',
  NOTION_API_TOKEN = 'notion_api_token',
  TERRAFORM_CLOUD_TOKEN = 'terraform_cloud_token',
  LINEAR_API_KEY = 'linear_api_key',
  SENTRY_AUTH_TOKEN = 'sentry_auth_token',
  FIGMA_PERSONAL_ACCESS_TOKEN = 'figma_personal_access_token',
  GRAFANA_API_KEY = 'grafana_api_key',
  DROPBOX_SHORT_LIVED_TOKEN = 'dropbox_short_lived_token',
  GITHUB_FINE_GRAINED_PAT = 'github_fine_grained_pat',
  SLACK_APP_LEVEL_TOKEN = 'slack_app_level_token',
  ASANA_PERSONAL_ACCESS_TOKEN = 'asana_personal_access_token',
  BITBUCKET_ACCESS_TOKEN = 'bitbucket_access_token',
  SUPABASE_PERSONAL_ACCESS_TOKEN = 'supabase_personal_access_token',
  RENDER_API_KEY = 'render_api_key',
  CONTENTFUL_PERSONAL_ACCESS_TOKEN = 'contentful_personal_access_token',
  FLY_IO_API_TOKEN = 'fly_io_api_token',
  LAUNCHDARKLY_API_ACCESS_TOKEN = 'launchdarkly_api_access_token',
  DOPPLER_TOKEN = 'doppler_token',
  CLICKUP_PERSONAL_API_TOKEN = 'clickup_personal_api_token',
  GENERIC_HIGH_ENTROPY = 'generic_high_entropy',
}

// Mirrors the CHECKERS map keys in apps/api's live-key-validator.adapter.ts
// - the only secret types with a live "is this key still active" check.
// Testing any other type always resolves to unknown, so the Testing tab
// only ever offers these.
export const TESTABLE_SECRET_TYPES: readonly ESecretType[] = [
  ESecretType.TELEGRAM_BOT_TOKEN,
  ESecretType.GITHUB_PAT,
  ESecretType.GITHUB_OAUTH_TOKEN,
  ESecretType.GITLAB_PAT,
  ESecretType.NPM_ACCESS_TOKEN,
  ESecretType.OPENAI_API_KEY,
  ESecretType.ANTHROPIC_API_KEY,
  ESecretType.STRIPE_LIVE_SECRET_KEY,
  ESecretType.STRIPE_TEST_SECRET_KEY,
  ESecretType.STRIPE_RESTRICTED_KEY,
  ESecretType.SLACK_TOKEN,
  ESecretType.DISCORD_BOT_TOKEN,
  ESecretType.DISCORD_WEBHOOK_URL,
  ESecretType.SENDGRID_API_KEY,
  ESecretType.MAILGUN_API_KEY,
  ESecretType.MAILCHIMP_API_KEY,
  ESecretType.SQUARE_ACCESS_TOKEN,
  ESecretType.DIGITALOCEAN_PAT,
  ESecretType.DIGITALOCEAN_OAUTH_TOKEN,
  ESecretType.AIRTABLE_API_KEY,
  ESecretType.NOTION_API_TOKEN,
  ESecretType.TERRAFORM_CLOUD_TOKEN,
  ESecretType.LINEAR_API_KEY,
  ESecretType.SENTRY_AUTH_TOKEN,
  ESecretType.FIGMA_PERSONAL_ACCESS_TOKEN,
  ESecretType.NEW_RELIC_API_KEY,
  ESecretType.POSTMAN_API_KEY,
  ESecretType.DROPBOX_SHORT_LIVED_TOKEN,
  ESecretType.FACEBOOK_ACCESS_TOKEN,
  ESecretType.TWITTER_BEARER_TOKEN,
  ESecretType.GITHUB_FINE_GRAINED_PAT,
  ESecretType.ASANA_PERSONAL_ACCESS_TOKEN,
  ESecretType.BITBUCKET_ACCESS_TOKEN,
  ESecretType.SUPABASE_PERSONAL_ACCESS_TOKEN,
  ESecretType.RENDER_API_KEY,
  ESecretType.CONTENTFUL_PERSONAL_ACCESS_TOKEN,
  ESecretType.FLY_IO_API_TOKEN,
  ESecretType.LAUNCHDARKLY_API_ACCESS_TOKEN,
  ESecretType.DOPPLER_TOKEN,
  ESecretType.CLICKUP_PERSONAL_API_TOKEN,
];
