// Mirrored 1:1 from apps/api's domain/constant/secret-type.constant.ts.
// No shared package between the two apps, so this is kept in sync by hand
// (same approach datatector's own web app takes for its enums).
export enum ESecretType {
  AWS_ACCESS_KEY_ID = 'aws_access_key_id',
  GITHUB_PAT = 'github_pat',
  GITHUB_OAUTH_TOKEN = 'github_oauth_token',
  GITHUB_APP_TOKEN = 'github_app_token',
  GITHUB_REFRESH_TOKEN = 'github_refresh_token',
  GITLAB_PAT = 'gitlab_pat',
  SLACK_TOKEN = 'slack_token',
  SLACK_WEBHOOK_URL = 'slack_webhook_url',
  STRIPE_LIVE_SECRET_KEY = 'stripe_live_secret_key',
  STRIPE_TEST_SECRET_KEY = 'stripe_test_secret_key',
  STRIPE_LIVE_PUBLISHABLE_KEY = 'stripe_live_publishable_key',
  STRIPE_RESTRICTED_KEY = 'stripe_restricted_key',
  TWILIO_API_KEY = 'twilio_api_key',
  TWILIO_ACCOUNT_SID = 'twilio_account_sid',
  SENDGRID_API_KEY = 'sendgrid_api_key',
  MAILGUN_API_KEY = 'mailgun_api_key',
  MAILCHIMP_API_KEY = 'mailchimp_api_key',
  SQUARE_ACCESS_TOKEN = 'square_access_token',
  SQUARE_OAUTH_SECRET = 'square_oauth_secret',
  NPM_ACCESS_TOKEN = 'npm_access_token',
  PYPI_UPLOAD_TOKEN = 'pypi_upload_token',
  DOCKERHUB_PAT = 'dockerhub_pat',
  JWT_TOKEN = 'jwt_token',
  GOOGLE_API_KEY = 'google_api_key',
  GOOGLE_OAUTH_CLIENT_SECRET = 'google_oauth_client_secret',
  FIREBASE_CLOUD_MESSAGING_KEY = 'firebase_cloud_messaging_key',
  DISCORD_BOT_TOKEN = 'discord_bot_token',
  DISCORD_WEBHOOK_URL = 'discord_webhook_url',
  TELEGRAM_BOT_TOKEN = 'telegram_bot_token',
  SHOPIFY_ACCESS_TOKEN = 'shopify_access_token',
  SHOPIFY_SHARED_SECRET = 'shopify_shared_secret',
  SHOPIFY_PRIVATE_APP_TOKEN = 'shopify_private_app_token',
  FACEBOOK_ACCESS_TOKEN = 'facebook_access_token',
  TWITTER_BEARER_TOKEN = 'twitter_bearer_token',
  PRIVATE_KEY_PEM = 'private_key_pem',
  DIGITALOCEAN_PAT = 'digitalocean_pat',
  DIGITALOCEAN_OAUTH_TOKEN = 'digitalocean_oauth_token',
  PLANETSCALE_PASSWORD = 'planetscale_password',
  PLANETSCALE_API_TOKEN = 'planetscale_api_token',
  HASHICORP_VAULT_TOKEN = 'hashicorp_vault_token',
  AIRTABLE_API_KEY = 'airtable_api_key',
  OPENAI_API_KEY = 'openai_api_key',
  ANTHROPIC_API_KEY = 'anthropic_api_key',
  BRAINTREE_ACCESS_TOKEN = 'braintree_access_token',
  GENERIC_HIGH_ENTROPY = 'generic_high_entropy',
}
