import { ESecretType } from '../constant/secret-type.constant';

// Ported 1:1 from credsScrapper/app/detection/descriptions.py.
export const DESCRIPTIONS: Readonly<Record<ESecretType, string>> = {
  [ESecretType.AWS_ACCESS_KEY_ID]: 'AWS Access Key ID',
  [ESecretType.GITHUB_PAT]: 'GitHub Personal Access Token',
  [ESecretType.GITHUB_OAUTH_TOKEN]: 'GitHub OAuth Token',
  [ESecretType.GITHUB_APP_TOKEN]: 'GitHub App/Installation Token',
  [ESecretType.GITHUB_REFRESH_TOKEN]: 'GitHub Refresh Token',
  [ESecretType.GITLAB_PAT]: 'GitLab Personal Access Token',
  [ESecretType.SLACK_TOKEN]: 'Slack Token',
  [ESecretType.SLACK_WEBHOOK_URL]: 'Slack Incoming Webhook URL',
  [ESecretType.STRIPE_LIVE_SECRET_KEY]: 'Stripe Live Secret Key',
  [ESecretType.STRIPE_TEST_SECRET_KEY]: 'Stripe Test Secret Key',
  [ESecretType.STRIPE_LIVE_PUBLISHABLE_KEY]: 'Stripe Live Publishable Key',
  [ESecretType.STRIPE_RESTRICTED_KEY]: 'Stripe Restricted Key',
  [ESecretType.TWILIO_API_KEY]: 'Twilio API Key',
  [ESecretType.TWILIO_ACCOUNT_SID]: 'Twilio Account SID',
  [ESecretType.SENDGRID_API_KEY]: 'SendGrid API Key',
  [ESecretType.MAILGUN_API_KEY]: 'Mailgun API Key',
  [ESecretType.MAILCHIMP_API_KEY]: 'Mailchimp API Key',
  [ESecretType.SQUARE_ACCESS_TOKEN]: 'Square Access Token',
  [ESecretType.SQUARE_OAUTH_SECRET]: 'Square OAuth Secret',
  [ESecretType.NPM_ACCESS_TOKEN]: 'npm Access Token',
  [ESecretType.PYPI_UPLOAD_TOKEN]: 'PyPI Upload Token',
  [ESecretType.DOCKERHUB_PAT]: 'Docker Hub Personal Access Token',
  [ESecretType.JWT_TOKEN]: 'JSON Web Token (JWT)',
  [ESecretType.GOOGLE_API_KEY]: 'Google API Key',
  [ESecretType.GOOGLE_OAUTH_CLIENT_SECRET]: 'Google OAuth Client Secret',
  [ESecretType.FIREBASE_CLOUD_MESSAGING_KEY]: 'Firebase Cloud Messaging Server Key',
  [ESecretType.DISCORD_BOT_TOKEN]: 'Discord Bot Token',
  [ESecretType.DISCORD_WEBHOOK_URL]: 'Discord Webhook URL',
  [ESecretType.TELEGRAM_BOT_TOKEN]: 'Telegram Bot Token',
  [ESecretType.SHOPIFY_ACCESS_TOKEN]: 'Shopify Access Token',
  [ESecretType.SHOPIFY_SHARED_SECRET]: 'Shopify Shared Secret',
  [ESecretType.SHOPIFY_PRIVATE_APP_TOKEN]: 'Shopify Private App Token',
  [ESecretType.FACEBOOK_ACCESS_TOKEN]: 'Facebook Access Token',
  [ESecretType.TWITTER_BEARER_TOKEN]: 'Twitter/X Bearer Token',
  [ESecretType.PRIVATE_KEY_PEM]: 'Private Key (PEM)',
  [ESecretType.DIGITALOCEAN_PAT]: 'DigitalOcean Personal Access Token',
  [ESecretType.DIGITALOCEAN_OAUTH_TOKEN]: 'DigitalOcean OAuth Token',
  [ESecretType.PLANETSCALE_PASSWORD]: 'PlanetScale Database Password',
  [ESecretType.PLANETSCALE_API_TOKEN]: 'PlanetScale API Token',
  [ESecretType.HASHICORP_VAULT_TOKEN]: 'HashiCorp Vault Token',
  [ESecretType.AIRTABLE_API_KEY]: 'Airtable API Key',
  [ESecretType.OPENAI_API_KEY]: 'OpenAI API Key',
  [ESecretType.ANTHROPIC_API_KEY]: 'Anthropic API Key',
  [ESecretType.BRAINTREE_ACCESS_TOKEN]: 'Braintree/PayPal Access Token',
  [ESecretType.GENERIC_HIGH_ENTROPY]: 'Unidentified high-entropy secret (service unknown)',
};

export function describe(secretType: ESecretType): string {
  return DESCRIPTIONS[secretType] ?? secretType;
}
