import { ESecretType } from '../constant/secret-type.constant';

// Ported 1:1 from credsScrapper/app/detection/descriptions.py.
export const DESCRIPTIONS: Readonly<Record<ESecretType, string>> = {
  [ESecretType.AWS_ACCESS_KEY_ID]: 'AWS Access Key ID',
  [ESecretType.GITHUB_PAT]: 'GitHub Personal Access Token',
  [ESecretType.GITHUB_OAUTH_TOKEN]: 'GitHub OAuth Token',
  [ESecretType.GITHUB_APP_TOKEN]: 'GitHub App/Installation Token',
  [ESecretType.GITHUB_REFRESH_TOKEN]: 'GitHub Refresh Token',
  [ESecretType.GITLAB_PAT]: 'GitLab Personal Access Token',
  [ESecretType.SLACK_TOKEN]: 'Slack Token',
  [ESecretType.SLACK_WEBHOOK_URL]: 'Slack Incoming Webhook URL',
  [ESecretType.STRIPE_LIVE_SECRET_KEY]: 'Stripe Live Secret Key',
  [ESecretType.STRIPE_TEST_SECRET_KEY]: 'Stripe Test Secret Key',
  [ESecretType.STRIPE_LIVE_PUBLISHABLE_KEY]: 'Stripe Live Publishable Key',
  [ESecretType.STRIPE_RESTRICTED_KEY]: 'Stripe Restricted Key',
  [ESecretType.TWILIO_API_KEY]: 'Twilio API Key',
  [ESecretType.TWILIO_ACCOUNT_SID]: 'Twilio Account SID',
  [ESecretType.SENDGRID_API_KEY]: 'SendGrid API Key',
  [ESecretType.MAILGUN_API_KEY]: 'Mailgun API Key',
  [ESecretType.MAILCHIMP_API_KEY]: 'Mailchimp API Key',
  [ESecretType.SQUARE_ACCESS_TOKEN]: 'Square Access Token',
  [ESecretType.SQUARE_OAUTH_SECRET]: 'Square OAuth Secret',
  [ESecretType.NPM_ACCESS_TOKEN]: 'npm Access Token',
  [ESecretType.PYPI_UPLOAD_TOKEN]: 'PyPI Upload Token',
  [ESecretType.DOCKERHUB_PAT]: 'Docker Hub Personal Access Token',
  [ESecretType.JWT_TOKEN]: 'JSON Web Token (JWT)',
  [ESecretType.GOOGLE_API_KEY]: 'Google API Key',
  [ESecretType.GOOGLE_OAUTH_CLIENT_SECRET]: 'Google OAuth Client Secret',
  [ESecretType.FIREBASE_CLOUD_MESSAGING_KEY]: 'Firebase Cloud Messaging Server Key',
  [ESecretType.DISCORD_BOT_TOKEN]: 'Discord Bot Token',
  [ESecretType.DISCORD_WEBHOOK_URL]: 'Discord Webhook URL',
  [ESecretType.TELEGRAM_BOT_TOKEN]: 'Telegram Bot Token',
  [ESecretType.SHOPIFY_ACCESS_TOKEN]: 'Shopify Access Token',
  [ESecretType.SHOPIFY_SHARED_SECRET]: 'Shopify Shared Secret',
  [ESecretType.SHOPIFY_PRIVATE_APP_TOKEN]: 'Shopify Private App Token',
  [ESecretType.FACEBOOK_ACCESS_TOKEN]: 'Facebook Access Token',
  [ESecretType.TWITTER_BEARER_TOKEN]: 'Twitter/X Bearer Token',
  [ESecretType.PRIVATE_KEY_PEM]: 'Private Key (PEM)',
  [ESecretType.DIGITALOCEAN_PAT]: 'DigitalOcean Personal Access Token',
  [ESecretType.DIGITALOCEAN_OAUTH_TOKEN]: 'DigitalOcean OAuth Token',
  [ESecretType.PLANETSCALE_PASSWORD]: 'PlanetScale Database Password',
  [ESecretType.PLANETSCALE_API_TOKEN]: 'PlanetScale API Token',
  [ESecretType.HASHICORP_VAULT_TOKEN]: 'HashiCorp Vault Token',
  [ESecretType.AIRTABLE_API_KEY]: 'Airtable API Key',
  [ESecretType.OPENAI_API_KEY]: 'OpenAI API Key',
  [ESecretType.ANTHROPIC_API_KEY]: 'Anthropic API Key',
  [ESecretType.BRAINTREE_ACCESS_TOKEN]: 'Braintree/PayPal Access Token',
  [ESecretType.OPENSSH_PRIVATE_KEY]: 'OpenSSH Private Key',
  [ESecretType.PGP_PRIVATE_KEY_BLOCK]: 'PGP Private Key Block',
  [ESecretType.GCP_SERVICE_ACCOUNT_KEY]: 'GCP Service Account Key (JSON)',
  [ESecretType.AZURE_STORAGE_ACCOUNT_KEY]: 'Azure Storage Account Key',
  [ESecretType.NEW_RELIC_API_KEY]: 'New Relic API Key',
  [ESecretType.POSTMAN_API_KEY]: 'Postman API Key',
  [ESecretType.DATABRICKS_TOKEN]: 'Databricks Personal Access Token',
  [ESecretType.NOTION_API_TOKEN]: 'Notion Integration Token',
  [ESecretType.TERRAFORM_CLOUD_TOKEN]: 'Terraform Cloud API Token',
  [ESecretType.LINEAR_API_KEY]: 'Linear API Key',
  [ESecretType.SENTRY_AUTH_TOKEN]: 'Sentry Auth Token',
  [ESecretType.FIGMA_PERSONAL_ACCESS_TOKEN]: 'Figma Personal Access Token',
  [ESecretType.GRAFANA_API_KEY]: 'Grafana API Key',
  [ESecretType.DROPBOX_SHORT_LIVED_TOKEN]: 'Dropbox Short-Lived Access Token',
  [ESecretType.GITHUB_FINE_GRAINED_PAT]: 'GitHub Fine-Grained Personal Access Token',
  [ESecretType.SLACK_APP_LEVEL_TOKEN]: 'Slack App-Level Token',
  [ESecretType.ASANA_PERSONAL_ACCESS_TOKEN]: 'Asana Personal Access Token',
  [ESecretType.BITBUCKET_ACCESS_TOKEN]: 'Bitbucket Access Token',
  [ESecretType.SUPABASE_PERSONAL_ACCESS_TOKEN]: 'Supabase Personal Access Token',
  [ESecretType.RENDER_API_KEY]: 'Render API Key',
  [ESecretType.CONTENTFUL_PERSONAL_ACCESS_TOKEN]: 'Contentful Personal Access Token',
  [ESecretType.FLY_IO_API_TOKEN]: 'Fly.io API Token',
  [ESecretType.LAUNCHDARKLY_API_ACCESS_TOKEN]: 'LaunchDarkly API Access Token',
  [ESecretType.DOPPLER_TOKEN]: 'Doppler Token',
  [ESecretType.CLICKUP_PERSONAL_API_TOKEN]: 'ClickUp Personal API Token',
  [ESecretType.GENERIC_HIGH_ENTROPY]: 'Unidentified high-entropy secret (service unknown)',
};

export function describe(secretType: ESecretType): string {
  return DESCRIPTIONS[secretType] ?? secretType;
}
